### ISSUE TITLE
[Feature Request] Choose different Discord activities depending on the player.

### ISSUE THREAD

**Issue by 0x4c756e61** [patryk-ku/mpris-discord-rpc#18]
Since not all players play music, it would be very cool if we could map a player to a discord activity. 

For example, having Delfin and the JellyFin client saying "watching" and some music players "listening".

I suggest something like this for the config file:

```yml
# Will use the "watching" activity
video_players:
   - "Delfin"

# Will use the "listening" activity
music_players:
   - "Elisa"
   - "AudioTube"
```
